name: Auto release on Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  set_tags:
    name: Set Tags
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.set_version_tag.outputs.version_tag }}
    steps:
      - name: Set up the version tag
        id: set_version_tag
        run: |
          echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  create_draft_release:
    name: Create Draft Release
    needs: set_tags
    uses: ./.github/workflows/auto-changelog.yaml
    with:
      name: Auto Changelog ${{ needs.set_tags.outputs.version_tag }}
      version_tag: ${{ needs.set_tags.outputs.version_tag }}
